"""

Revision ID: 0ee40ea22c7c
Revises: 9e268d8b8440
Create Date: 2021-01-31 14:43:22.899709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ee40ea22c7c'
down_revision = '9e268d8b8440'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
