"""

Revision ID: 562dbb420294
Revises: c2cca33ef814
Create Date: 2020-11-02 07:50:59.052071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '562dbb420294'
down_revision = 'c2cca33ef814'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('studyattribute')
    op.drop_constraint('attribute_studyitem_id_fkey', 'attribute', type_='foreignkey')
    op.drop_column('attribute', 'studyitem_id')
    op.add_column('trade', sa.Column('correlated_position', sa.Boolean(), nullable=True))
    op.add_column('trade', sa.Column('entry_price', sa.Float(), nullable=True))
    op.add_column('trade', sa.Column('full_stop', sa.Boolean(), nullable=True))
    op.add_column('trade', sa.Column('scaled_in', sa.Boolean(), nullable=True))
    op.add_column('trade', sa.Column('scaled_out', sa.Boolean(), nullable=True))
    op.add_column('trade', sa.Column('sl', sa.Integer(), nullable=True))
    op.add_column('trade', sa.Column('sl_price', sa.Float(), nullable=True))
    op.add_column('trade', sa.Column('tp', sa.Integer(), nullable=True))
    op.add_column('trade', sa.Column('tp_exceeded', sa.Boolean(), nullable=True))
    op.add_column('trade', sa.Column('tp_price', sa.Float(), nullable=True))
    op.add_column('trade', sa.Column('tp_reached', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trade', 'tp_reached')
    op.drop_column('trade', 'tp_price')
    op.drop_column('trade', 'tp_exceeded')
    op.drop_column('trade', 'tp')
    op.drop_column('trade', 'sl_price')
    op.drop_column('trade', 'sl')
    op.drop_column('trade', 'scaled_out')
    op.drop_column('trade', 'scaled_in')
    op.drop_column('trade', 'full_stop')
    op.drop_column('trade', 'entry_price')
    op.drop_column('trade', 'correlated_position')
    op.add_column('attribute', sa.Column('studyitem_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('attribute_studyitem_id_fkey', 'attribute', 'studyitem', ['studyitem_id'], ['id'], ondelete='RESTRICT')
    op.create_table('studyattribute',
    sa.Column('study_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('attribute_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['attribute_id'], ['attribute.id'], name='studyattribute_attribute_id_fkey'),
    sa.ForeignKeyConstraint(['study_id'], ['study.id'], name='studyattribute_study_id_fkey'),
    sa.PrimaryKeyConstraint('study_id', 'attribute_id', name='studyattribute_pkey')
    )
    # ### end Alembic commands ###
