"""added lazy eager joined loading

Revision ID: 5b84aa64f783
Revises: 9b250638a123
Create Date: 2020-10-21 20:50:31.395713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b84aa64f783'
down_revision = '9b250638a123'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
