"""removed attrs in studyitem

Revision ID: 6e6c77304a27
Revises: ff05149ae55e
Create Date: 2020-10-24 21:33:36.314628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e6c77304a27'
down_revision = 'ff05149ae55e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
