"""

Revision ID: 89a20bee65a5
Revises: 0ee40ea22c7c
Create Date: 2021-01-31 14:43:32.287331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89a20bee65a5'
down_revision = '0ee40ea22c7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
