"""added study item attrs 2

Revision ID: ff05149ae55e
Revises: dffed5f79331
Create Date: 2020-10-24 20:45:23.863219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff05149ae55e'
down_revision = 'dffed5f79331'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attribute',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attribute_id'), 'attribute', ['id'], unique=False)
    op.create_table('studyattribute',
    sa.Column('study_id', sa.Integer(), nullable=False),
    sa.Column('attribute_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attribute_id'], ['attribute.id'], ),
    sa.ForeignKeyConstraint(['study_id'], ['study.id'], ),
    sa.PrimaryKeyConstraint('study_id', 'attribute_id')
    )
    op.drop_index('ix_studyattributes_id', table_name='studyattributes')
    op.drop_table('studyattributes')
    op.alter_column('studyitem', 'instrument_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('studyitem', 'style_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('studyitem', 'style_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('studyitem', 'instrument_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('studyattributes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='studyattributes_pkey')
    )
    op.create_index('ix_studyattributes_id', 'studyattributes', ['id'], unique=False)
    op.drop_table('studyattribute')
    op.drop_index(op.f('ix_attribute_id'), table_name='attribute')
    op.drop_table('attribute')
    # ### end Alembic commands ###
