"""chabged date to string to trade

Revision ID: 1fbab5d5ba08
Revises: 4cdc4288f09d
Create Date: 2020-05-30 22:23:24.263759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fbab5d5ba08'
down_revision = '4cdc4288f09d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
