"""added db constraints

Revision ID: 3bb1b1fd93ab
Revises: 4da0041686a4
Create Date: 2020-10-21 20:29:41.808918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bb1b1fd93ab'
down_revision = '4da0041686a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('strategyimage', 'strategy_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('strategyimage_strategy_id_fkey', 'strategyimage', type_='foreignkey')
    op.create_foreign_key(None, 'strategyimage', 'strategy', ['strategy_id'], ['id'], ondelete='CASCADE')
    op.alter_column('studyitem', 'study_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('studyitem_study_id_fkey', 'studyitem', type_='foreignkey')
    op.create_foreign_key(None, 'studyitem', 'study', ['study_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('studyitemimage', 'studyitem_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('studyitemimage_studyitem_id_fkey', 'studyitemimage', type_='foreignkey')
    op.create_foreign_key(None, 'studyitemimage', 'studyitem', ['studyitem_id'], ['id'], ondelete='CASCADE')
    op.alter_column('trade', 'instrument_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('trade', 'strategy_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('trade', 'style_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('trade_strategy_id_fkey', 'trade', type_='foreignkey')
    op.drop_constraint('trade_style_id_fkey', 'trade', type_='foreignkey')
    op.drop_constraint('trade_instrument_id_fkey', 'trade', type_='foreignkey')
    op.create_foreign_key(None, 'trade', 'instrument', ['instrument_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'trade', 'strategy', ['strategy_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'trade', 'style', ['style_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('tradeimage', 'trade_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('tradeimage_trade_id_fkey', 'tradeimage', type_='foreignkey')
    op.create_foreign_key(None, 'tradeimage', 'trade', ['trade_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('watchlist_instrument_id_fkey', 'watchlist', type_='foreignkey')
    op.drop_column('watchlist', 'instrument_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watchlist', sa.Column('instrument_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('watchlist_instrument_id_fkey', 'watchlist', 'instrument', ['instrument_id'], ['id'])
    op.drop_constraint(None, 'tradeimage', type_='foreignkey')
    op.create_foreign_key('tradeimage_trade_id_fkey', 'tradeimage', 'trade', ['trade_id'], ['id'])
    op.alter_column('tradeimage', 'trade_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'trade', type_='foreignkey')
    op.drop_constraint(None, 'trade', type_='foreignkey')
    op.drop_constraint(None, 'trade', type_='foreignkey')
    op.create_foreign_key('trade_instrument_id_fkey', 'trade', 'instrument', ['instrument_id'], ['id'])
    op.create_foreign_key('trade_style_id_fkey', 'trade', 'style', ['style_id'], ['id'])
    op.create_foreign_key('trade_strategy_id_fkey', 'trade', 'strategy', ['strategy_id'], ['id'])
    op.alter_column('trade', 'style_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('trade', 'strategy_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('trade', 'instrument_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'studyitemimage', type_='foreignkey')
    op.create_foreign_key('studyitemimage_studyitem_id_fkey', 'studyitemimage', 'studyitem', ['studyitem_id'], ['id'])
    op.alter_column('studyitemimage', 'studyitem_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'studyitem', type_='foreignkey')
    op.create_foreign_key('studyitem_study_id_fkey', 'studyitem', 'study', ['study_id'], ['id'])
    op.alter_column('studyitem', 'study_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'strategyimage', type_='foreignkey')
    op.create_foreign_key('strategyimage_strategy_id_fkey', 'strategyimage', 'strategy', ['strategy_id'], ['id'])
    op.alter_column('strategyimage', 'strategy_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
