"""removed attrs in studyitem sd

Revision ID: 49416a4ec51f
Revises: 7faff1bd719a
Create Date: 2020-10-24 21:53:25.862274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49416a4ec51f'
down_revision = '7faff1bd719a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
