"""Added date.now to trade

Revision ID: 4cdc4288f09d
Revises: a8204f515bcf
Create Date: 2020-05-30 22:10:08.350564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cdc4288f09d'
down_revision = 'a8204f515bcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
