"""back populates to backrefs for stra images

Revision ID: 4d883b1ac286
Revises: b1ce1ca11b77
Create Date: 2020-05-25 12:52:47.870761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d883b1ac286'
down_revision = 'b1ce1ca11b77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
