"""removed attrs in studyitem d

Revision ID: 5cb038a307e8
Revises: 6e6c77304a27
Create Date: 2020-10-24 21:37:38.384682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cb038a307e8'
down_revision = '6e6c77304a27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
