"""removed attrs in studyitem s

Revision ID: 7faff1bd719a
Revises: 281f765bef0b
Create Date: 2020-10-24 21:50:16.608920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7faff1bd719a'
down_revision = '281f765bef0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
