"""Added date.now to trade

Revision ID: 859e9d1d977d
Revises: 1fbab5d5ba08
Create Date: 2020-05-30 22:31:16.591652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '859e9d1d977d'
down_revision = '1fbab5d5ba08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
