"""Added Trading Plan Model

Revision ID: 955521a8cfcb
Revises: ac7907bc0935
Create Date: 2020-06-13 07:23:18.173488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '955521a8cfcb'
down_revision = 'ac7907bc0935'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
