"""added db constraints

Revision ID: 9b250638a123
Revises: 3bb1b1fd93ab
Create Date: 2020-10-21 20:30:12.205859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b250638a123'
down_revision = '3bb1b1fd93ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
