"""

Revision ID: a54a78133010
Revises: 859e9d1d977d
Create Date: 2020-06-09 22:50:09.046734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a54a78133010'
down_revision = '859e9d1d977d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategyimage', sa.Column('location', sa.String(), nullable=True))
    op.add_column('tradeimage', sa.Column('location', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tradeimage', 'location')
    op.drop_column('strategyimage', 'location')
    # ### end Alembic commands ###
