"""droped image large binary

Revision ID: ac7907bc0935
Revises: a54a78133010
Create Date: 2020-06-09 23:24:52.452798

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ac7907bc0935'
down_revision = 'a54a78133010'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategyimage', 'image')
    op.drop_column('tradeimage', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tradeimage', sa.Column('image', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.add_column('strategyimage', sa.Column('image', postgresql.BYTEA(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
