"""back populates to backrefs

Revision ID: b1ce1ca11b77
Revises: d8ef1fca2e17
Create Date: 2020-05-25 11:33:14.840318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1ce1ca11b77'
down_revision = 'd8ef1fca2e17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trade', sa.Column('instrument_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'trade', 'instrument', ['instrument_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trade', type_='foreignkey')
    op.drop_column('trade', 'instrument_id')
    # ### end Alembic commands ###
