"""attr si changed to nullable alow

Revision ID: c2cca33ef814
Revises: c3ad2916e448
Create Date: 2020-10-25 09:43:00.458360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2cca33ef814'
down_revision = 'c3ad2916e448'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attribute', 'studyitem_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('attribute_studyitem_id_fkey', 'attribute', type_='foreignkey')
    op.create_foreign_key(None, 'attribute', 'studyitem', ['studyitem_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attribute', type_='foreignkey')
    op.create_foreign_key('attribute_studyitem_id_fkey', 'attribute', 'studyitem', ['studyitem_id'], ['id'], ondelete='CASCADE')
    op.alter_column('attribute', 'studyitem_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
