"""changed attr linkaged from MTM to MTO

Revision ID: c3ad2916e448
Revises: a577e4d52ddd
Create Date: 2020-10-25 09:19:52.070703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3ad2916e448'
down_revision = 'a577e4d52ddd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attribute', sa.Column('study_id', sa.Integer(), nullable=False))
    op.add_column('attribute', sa.Column('studyitem_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'attribute', 'studyitem', ['studyitem_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'attribute', 'study', ['study_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attribute', type_='foreignkey')
    op.drop_constraint(None, 'attribute', type_='foreignkey')
    op.drop_column('attribute', 'studyitem_id')
    op.drop_column('attribute', 'study_id')
    # ### end Alembic commands ###
