"""added study item attrs

Revision ID: dffed5f79331
Revises: 5b84aa64f783
Create Date: 2020-10-24 13:06:36.663134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dffed5f79331'
down_revision = '5b84aa64f783'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('studyattributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_studyattributes_id'), 'studyattributes', ['id'], unique=False)
    op.drop_index('ix_tradeattributes_id', table_name='tradeattributes')
    op.drop_table('tradeattributes')
    op.add_column('studyitem', sa.Column('date', sa.DateTime(), nullable=True))
    op.add_column('studyitem', sa.Column('instrument_id', sa.Integer(), nullable=True))
    op.add_column('studyitem', sa.Column('outcome', sa.Boolean(), nullable=True))
    op.add_column('studyitem', sa.Column('pips', sa.Integer(), nullable=True))
    op.add_column('studyitem', sa.Column('position', sa.Boolean(), nullable=True))
    op.add_column('studyitem', sa.Column('rrr', sa.Float(), nullable=True))
    op.add_column('studyitem', sa.Column('style_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'studyitem', 'style', ['style_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'studyitem', 'instrument', ['instrument_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'studyitem', type_='foreignkey')
    op.drop_constraint(None, 'studyitem', type_='foreignkey')
    op.drop_column('studyitem', 'style_id')
    op.drop_column('studyitem', 'rrr')
    op.drop_column('studyitem', 'position')
    op.drop_column('studyitem', 'pips')
    op.drop_column('studyitem', 'outcome')
    op.drop_column('studyitem', 'instrument_id')
    op.drop_column('studyitem', 'date')
    op.create_table('tradeattributes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='tradeattributes_pkey')
    )
    op.create_index('ix_tradeattributes_id', 'tradeattributes', ['id'], unique=False)
    op.drop_index(op.f('ix_studyattributes_id'), table_name='studyattributes')
    op.drop_table('studyattributes')
    # ### end Alembic commands ###
