"""added studyitem attrs

Revision ID: fc5cc3714f26
Revises: 49416a4ec51f
Create Date: 2020-10-24 21:59:36.618590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc5cc3714f26'
down_revision = '49416a4ec51f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('studyitemattribute',
    sa.Column('studyitem_id', sa.Integer(), nullable=False),
    sa.Column('attribute_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attribute_id'], ['attribute.id'], ),
    sa.ForeignKeyConstraint(['studyitem_id'], ['studyitem.id'], ),
    sa.PrimaryKeyConstraint('studyitem_id', 'attribute_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('studyitemattribute')
    # ### end Alembic commands ###
